import Graph from "../classes/Graph";

const urlProject = "/[category]/[name]";

export const graph42 = () =>
  new Graph({
    nodes: [
      {
        color: "white",
        layer: 0,
        text: "Projects",
        radians: 1,
        velocity: 0.00005,
        x: 0,
        y: 0,
        url: "/[category]",
        as: "/all",
      },
      {
        color: "white",
        layer: 1,
        text: "TOZ",
        radians: 5,
        velocity: 0.0055,
        x: 0,
        y: 0,
        url: urlProject,
        as: "/personal/toz",
      },
      {
        color: "white",
        layer: 1,
        text: "cub3D",
        radians: 2,
        velocity: 0.0055,
        x: 0,
        y: 0,
        url: urlProject,
        as: "/42/cub3D",
      },
      {
        color: "white",
        layer: 2,
        text: "minishell",
        radians: 0.5,
        velocity: 0.0045,
        x: 0,
        y: 0,
        url: urlProject,
        as: "/42/minishell",
      },
      {
        color: "white",
        layer: 2,
        text: "ft-services",
        radians: 2.75,
        velocity: 0.0045,
        x: 0,
        y: 0,
        url: urlProject,
        as: "/42/ft-services",
      },
      {
        color: "white",
        layer: 2,
        text: "libasm",
        radians: 4.6,
        velocity: 0.0045,
        x: 0,
        y: 0,
        url: urlProject,
        as: "/42/libasm",
      },
      {
        color: "white",
        layer: 3,
        text: "philosophers",
        radians: 0.5,
        velocity: 0.003,
        x: 0,
        y: 0,
        url: urlProject,
        as: "/42/philosophers",
      },
      {
        color: "white",
        layer: 3,
        text: "ft-containers",
        radians: 2.5,
        velocity: 0.003,
        x: 0,
        y: 0,
        url: urlProject,
        as: "/42/ft-containers",
      },
    ],
    containerId: `galaxy-container-42`,
  });
